### ISSUE TITLE
Reading writing files on the sdio card

### ISSUE THREAD

**Issue by ceigel** [jkristell/feather-f405#4]
The embedded-sdmmc library is not used. It would be great if the sdio example would read/write files.

**Comment by jkristell** [comment]
I have a example of that somewhere in some local repo. Can see if I can find it and add it to the repo.

**Comment by jkristell** [comment]
https://github.com/jkristell/feather-f405/blob/add-embedded-sdmmc-example/examples/sd-sdmmc-read-fat.rs

Only compile tested. But should work as a starting point.

**Comment by ceigel** [comment]
Cool, thanks. I will give it a shot this weekend.

**Comment by ceigel** [comment]
I managed to try this example, however it doesn't work. Unfortunately I didn't have time to debug it. Here is the output.
`OK!
Card size...
size: Ok(15523840)
Volume 0...
Err: DeviceError(DataCrcFail)
`

I tried to simplify the example a bit: https://github.com/ceigel/feather-f405/blob/add-embedded-sdmmc-example/examples/sd-usb-mass-storage.rs

**Comment by jkristell** [comment]
You could try and use a lower clock frequency to the card.
